export const ENV = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  DATABASE_URL: 'DATABASE_URL',
  JWT_SECRET: 'JWT_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  JWT_EXPIRY: 'JWT_EXPIRY',
  REDIS_URL: 'REDIS_URL',
  BCRYPT_ROUNDS: 'BCRYPT_ROUNDS',
  ALLOWED_ORIGINS: 'ALLOWED_ORIGINS',
  LOG_LEVEL: 'LOG_LEVEL',
  RATE_LIMIT_WINDOW_MS: 'RATE_LIMIT_WINDOW_MS',
  RATE_LIMIT_MAX: 'RATE_LIMIT_MAX',
} as const;

export const ENV_DEFAULTS = {
  PORT: 3000,
  JWT_EXPIRY: '15m',
  BCRYPT_ROUNDS: 12,
  LOG_LEVEL: 'info',
  RATE_LIMIT_WINDOW_MS: 60_000,
  RATE_LIMIT_MAX: 100,
} as const;

export type EnvKey = (typeof ENV)[keyof typeof ENV];
